module.exports = {
  INVALID_PROVIDER: 'INVALID_PROVIDER',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',
  INVALID_PASSWORD_LENGTH: 'INVALID_PASSWORD_LENGTH',
  WRONG_USERNAME_OR_PASSWORD: 'WRONG_USERNAME_OR_PASSWORD',
  INVALID_GENDER: 'INVALID_GENDER',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  UNSUPPORTED_ROLE: 'UNSUPPORTED_ROLE',
  PERMISSION_DENIED: 'PERMISSION_DENIED',
  UNAUTHORIZED: 'UNAUTHORIZED',

  // property
  PROPERTY_NAME_ALREADY_EXISTS: 'PROPERTY_NAME_ALREADY_EXISTS',
  PROPERTY_NOT_FOUND: 'PROPERTY_NOT_FOUND',
  PROPERTY_ADDRESS_ALREADY_EXISTS: 'PROPERTY_ADDRESS_ALREADY_EXISTS',

  // property and unit
  REQUIRED_MINIMUM_ONE_UNIT: 'REQUIRED_MINIMUM_ONE_UNIT',

  // unit and lease
  UNIT_NOT_FOUND: 'UNIT_NOT_FOUND',
  UNIT_NAME_ALREADY_EXISTS: 'UNIT_NAME_ALREADY_EXISTS',
  UNIT_ALREADY_HAS_LEASE: 'UNIT_ALREADY_HAS_LEASE',
  INVALID_START_END_DATES_INTERVAL: 'INVALID_START_END_DATES_INTERVAL',
  UNIT_HAS_NOT_LEASE: 'UNIT_HAS_NOT_LEASE',

  TENANT_ALREADY_CONNECTED_TO_UNIT: 'TENANT_ALREADY_CONNECTED_TO_UNIT',

  // x-token
  X_TOKEN_REQUIRED: 'X_TOKEN_REQUIRED',
  INVALID_X_TOKEN: 'INVALID_X_TOKEN'
};
